import { Router } from "express";
import { requireAuth } from "../middleware/auth";
import { requireRole } from "../middleware/rbac";
import { createDoctorProfile, markDoctorLeave, listDoctors, getPlatformStats, listAllAppointments, adminCancelAppointment, setDoctorActive, listUpcomingLeaves, deleteLeave, listUsers, setUserActive, setUserRole, } from "../controllers/adminController";
const router = Router();
router.use(requireAuth, requireRole("admin"));
router.get("/doctors", listDoctors);
router.post("/doctors", createDoctorProfile);
router.patch("/doctors/:userId/active", setDoctorActive);
router.post("/leave", markDoctorLeave);
router.get("/leaves", listUpcomingLeaves);
router.delete("/leaves/:id", deleteLeave);
router.get("/stats", getPlatformStats);
router.get("/appointments", listAllAppointments);
router.post("/appointments/:id/cancel", adminCancelAppointment);
router.get("/users", listUsers);
router.patch("/users/:userId/active", setUserActive);
router.patch("/users/:userId/role", setUserRole);
export default router;
