import { Router } from "express";
import { register, login, updateMe } from "../controllers/authController";
import { startGoogleOAuth, handleGoogleOAuthCallback, getCalendarLinkStatus, } from "../controllers/googleAuthController";
import { requireAuth } from "../middleware/auth";
const router = Router();
router.post("/register", register);
router.post("/login", login);
router.put("/me", requireAuth, updateMe);
router.get("/google", requireAuth, startGoogleOAuth);
router.get("/google/callback", handleGoogleOAuthCallback);
router.get("/calendar/status", requireAuth, getCalendarLinkStatus);
export default router;
